//! A separate test binary gives Tauri an undriven current-thread runtime: IPC
//! dispatch and cancel finish before any queued async command can be polled.
use builderlab_auth::auth_storage::{
    FileSessionCredentialStorage, SessionCredentialStorage, SessionStorageKey,
    StoredSessionCredential,
};
use serde_json::json;
use std::sync::{
    atomic::{AtomicUsize, Ordering::SeqCst},
    Arc,
};
use tauri::{
    ipc::{CallbackFn, InvokeBody, InvokeResponse},
    test::{mock_builder, mock_context, noop_assets, MockRuntime, INVOKE_KEY},
    webview::InvokeRequest,
    WebviewWindow, WebviewWindowBuilder,
};
use tokio::sync::oneshot;

fn dispatch(
    window: &WebviewWindow<MockRuntime>,
    command: &str,
) -> oneshot::Receiver<InvokeResponse> {
    let (sender, receiver) = oneshot::channel();
    let webview: &tauri::Webview<MockRuntime> = window.as_ref();
    webview.clone().on_message(
        InvokeRequest {
            cmd: format!("plugin:builderlab|{command}"),
            callback: CallbackFn(0),
            error: CallbackFn(1),
            url: if cfg!(windows) {
                "http://tauri.localhost"
            } else {
                "tauri://localhost"
            }
            .parse()
            .unwrap(),
            body: InvokeBody::default(),
            headers: Default::default(),
            invoke_key: INVOKE_KEY.into(),
        },
        Box::new(move |_, _, response, _, _| {
            sender.send(response).unwrap();
        }),
    );
    receiver
}

async fn response(
    receiver: oneshot::Receiver<InvokeResponse>,
) -> Result<serde_json::Value, serde_json::Value> {
    match tokio::time::timeout(std::time::Duration::from_secs(5), receiver)
        .await
        .unwrap()
        .unwrap()
    {
        InvokeResponse::Ok(body) => Ok(body.deserialize().unwrap()),
        InvokeResponse::Err(error) => Err(error.0),
    }
}

#[test]
fn cancellation_and_supersession_cover_unpolled_tauri_login_commands() {
    let dir = tempfile::tempdir().unwrap();
    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .unwrap();
    tauri::async_runtime::set(runtime.handle().clone());
    let checks = Arc::new(AtomicUsize::new(0));
    let counted = checks.clone();
    let listener = runtime
        .block_on(tokio::net::TcpListener::bind("127.0.0.1:0"))
        .unwrap();
    let base = format!("http://{}", listener.local_addr().unwrap());
    let server = axum::Router::new().route(
        "/api/goose/v1/auth/me",
        axum::routing::get(move || {
            counted.fetch_add(1, SeqCst);
            std::future::ready(axum::Json(
                json!({"subject": "test", "email": "test@example.com"}),
            ))
        }),
    );
    runtime.spawn(async move {
        axum::serve(listener, server).await.unwrap();
    });

    // This integration-test process has one test. Configure the real plugin
    // before constructing it; no user config, Keychain or browser is used.
    std::env::set_var("BL_HOME", dir.path());
    std::env::set_var("BL_SKILLS_CONFIG", dir.path().join("skills.yaml"));
    std::env::set_var("BL_SKILLS_PROFILE", "queued-login-test");
    std::env::set_var("BL_AUTH_STORAGE", "file");
    std::env::set_var("BL_AUTH_STORAGE_FILE", dir.path().join("sessions.json"));
    std::env::set_var("KGOOSE_BASE_URL", &base);
    std::env::set_var("KGOOSE_SERVICE_PATH", "/api/goose");
    let store = FileSessionCredentialStorage::new(dir.path().join("sessions.json"));
    let key = SessionStorageKey::from_profile_and_kgoose_base_url(
        "queued-login-test",
        &base,
        "/api/goose",
    );
    store
        .set(
            &key,
            &StoredSessionCredential {
                session_credential: "saved-by-cli".into(),
                expires_at: None,
            },
        )
        .unwrap();
    let mut context = mock_context(noop_assets());
    let permissions = [
        "default.toml",
        "autogenerated/commands/auth.toml",
        "autogenerated/commands/login.toml",
        "autogenerated/commands/cancel.toml",
        "autogenerated/commands/sign_out.toml",
    ]
    .map(|path| {
        toml::from_str(
            &std::fs::read_to_string(
                std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                    .join("permissions")
                    .join(path),
            )
            .unwrap(),
        )
        .unwrap()
    })
    .into_iter()
    .collect();
    *context.runtime_authority_mut() = tauri::runtime_authority!(
        [(
            "builderlab".into(),
            tauri::utils::acl::manifest::Manifest::new(permissions, None)
        )]
        .into(),
        Default::default()
    );
    let app = mock_builder()
        .plugin(tauri_plugin_builderlab::init())
        .build(context)
        .unwrap();
    let window = WebviewWindowBuilder::new(&app, "main", Default::default())
        .build()
        .unwrap();

    let login = dispatch(&window, "login");
    let mut cancel = dispatch(&window, "cancel");
    assert!(matches!(cancel.try_recv().unwrap(), InvokeResponse::Ok(_)));
    assert_eq!(
        runtime.block_on(response(login)),
        Err(json!("Builderlab authentication canceled"))
    );
    assert_eq!(checks.load(SeqCst), 0);
    assert_eq!(
        store.get(&key).unwrap().unwrap().session_credential,
        "saved-by-cli"
    );

    // A later attempt still works, and supersedes an older queued attempt even
    // if the executor polls the older task first.
    let first = dispatch(&window, "login");
    let second = dispatch(&window, "login");
    runtime.block_on(async {
        assert_eq!(
            response(first).await,
            Err(json!("Builderlab authentication canceled"))
        );
        assert_eq!(response(second).await.unwrap()["email"], "test@example.com");
    });
    assert_eq!(checks.load(SeqCst), 1);

    // Canceling with no saved session must also settle without opening a browser
    // or creating a session. No opener plugin is installed in this fixture.
    store.delete(&key).unwrap();
    let login = dispatch(&window, "login");
    let cancel = dispatch(&window, "cancel");
    runtime.block_on(async {
        response(cancel).await.unwrap();
        assert_eq!(
            response(login).await,
            Err(json!("Builderlab authentication canceled"))
        );
    });
    assert!(store.get(&key).unwrap().is_none());
    assert_eq!(checks.load(SeqCst), 1);
}
